version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - '4200:80'
    depends_on:
      - backend
    environment:
      - API_URL=http://localhost:5000
  backend:
    build: ./backend
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - JWT_KEY=${JWT_KEY}
    volumes:
      - uploads:/app/uploads
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  uploads:
  postgres-data:
